### ISSUE TITLE
Error and bugs after Godot 4.2 update

### ISSUE THREAD

**Issue by FootClanSoldier** [zaevi/godot-filesystem-view#4]
After updating to Godot 4.2 this plugin seems to have some bugs, most likely because of changed API.

I can no longer right click on files in the View and get this error message:

**res://addons/FileSystemView/FileSystemView.Popup.gd:75 - Cannot call method 'get_file_type' on a null value.
  res://addons/FileSystemView/plugin.gd:85 - Cannot call method 'get_root' on a null value.**

When I load my project I instantly get these messages:
(The first message might not be related to this plugin)

**modules/gdscript/gdscript_vm.cpp:1319 - Condition ' !nc ' is true. Breaking..:**

**res://addons/FileSystemView/FileSystemView.Popup.gd:48 - Internal script error! Opcode: 25 (please report).**

**Comment by zaevi** [comment]
Thanks for your report! 

Yes, there have been break changes since 4.2. I ported this plugin to 4.2 several weeks ago, but there is still some work I need to do before publishing it.

So, you can use the latest commit for now. I will keep this issue open until a new version is released.

**Comment by leon196** [comment]
Hello,

I have the same error in 4.3
`res://addons/FileSystemView/plugin.gd:85 - Cannot call method 'get_root' on a null value.`

And also this one:
`res://addons/FileSystemView/plugin.gd:78 - Invalid call. Nonexistent function '_select_file (via call)' in base 'FileSystemDock'.`

I'd like to help but I'm not sure what is the issue. It seems to occur line 85 were `func _notification(what):` is defined. Any ideas on what's happening under the hood?

**Comment by gruntmoon** [comment]
Since @zaevi havent update this plugin I tried to add 4.3+ support with a quick fix.
https://github.com/gruntmoon/godot-filesystem-view

Not ideal but seems like you can double click the files in FilesystemView and open them again.
Test .md .gd .cfg all opened in internal editor, as well as loading the .tscn.
Didnt think about external editor if anyone wants to improve please go ahead.

cc: @leon196 

Thanks.

**Comment by gruntmoon** [comment]
I have fixed more with the popup menu also fixed now.

**Comment by gruntmoon** [comment]
Add a PR:
* https://github.com/zaevi/godot-filesystem-view/pull/5

Thanks.

**Comment by leon196** [comment]
Fantastic news, thanks @gruntmoon to take the time, going to check this out

**Comment by gruntmoon** [comment]
No problem.

Double click on a `Textfile (txt cfg ini)` still sometimes fail but there are workarounds:
1. open the same file in default file manager
2. Or right click and open it.

Either one will make double click open again.
Not sure why.

Thanks.

**Comment by zaevi** [comment]
Reopen the issue as opening file is still not perfectly resolved...

**Comment by gruntmoon** [comment]
Thanks @zaevi for merging the PR. Not ideal fix but at least normal functionality is restored. 😄
